import nodemailer from "nodemailer";
import { logger } from "../utils/logger.js";

export async function sendTakedownEmail(report, customReason = null) {
  try {
    if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) {
      logger.warn('SMTP not configured, skipping email send');
      return { sent: false, message: 'SMTP not configured' };
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });

    const reason = customReason || generateReason(report);

    const mailOptions = {
      from: process.env.SMTP_FROM || `"PhishHawk" <${process.env.SMTP_USER}>`,
      to: process.env.EMAIL_TO || "report@apwg.org",
      subject: `Phishing Report - ${report.url}`,
      text: reason,
      html: generateEmailHTML(report, reason)
    };

    const result = await transporter.sendMail(mailOptions);
    
    logger.info(`Takedown email sent for ${report.url}`);
    
    return {
      sent: true,
      messageId: result.messageId,
      sentAt: new Date()
    };

  } catch (error) {
    logger.error(`Failed to send takedown email:`, error);
    return {
      sent: false,
      error: error.message
    };
  }
}

function generateReason(report) {
  return `
AUTOMATED PHISHING REPORT

URL: ${report.url}
Risk Score: ${report.riskScore}/100
Risk Level: ${report.riskLevel}
Detection Date: ${report.createdAt}

This URL has been automatically identified as a potential phishing threat based on the following analysis:

Risk Factors Detected:
${formatRiskChecks(report.riskChecks)}

${report.validationResults ? formatValidationResults(report.validationResults) : ''}

This automated report is generated by our phishing detection system. Please investigate and take appropriate action to protect users from this potential threat.

For questions or additional information, please contact our security team.

Best regards,
Automated Security Response Team
  `.trim();
}

function formatRiskChecks(checks) {
  if (!checks || typeof checks !== 'object') return '• Multiple risk indicators detected';
  
  const messages = [];
  
  if (checks.suspiciousTLD) messages.push('• Suspicious top-level domain detected');
  if (checks.suspiciousKeywords) messages.push(`• Suspicious keywords found: ${Array.isArray(checks.suspiciousKeywords) ? checks.suspiciousKeywords.join(', ') : checks.suspiciousKeywords}`);
  if (checks.excessiveSubdomains) messages.push(`• Excessive subdomains (${checks.excessiveSubdomains})`);
  if (checks.urlShortener) messages.push('• URL shortening service detected');
  if (checks.ipInDomain) messages.push('• IP address in domain name');
  if (checks.insecureProtocol) messages.push('• Insecure HTTP protocol');
  if (checks.passwordForm) messages.push('• Password collection form detected');
  if (checks.likelyLoginPage) messages.push('• Likely fake login page');
  if (checks.urgentLanguage) messages.push('• Urgent/threatening language detected');
  
  return messages.length > 0 ? messages.join('\n') : '• Multiple risk indicators detected';
}

function formatValidationResults(validation) {
  if (!validation) return '';
  
  let result = '\nThird-party Validation Results:\n';
  
  if (validation.virusTotal && !validation.virusTotal.error) {
    result += `• VirusTotal: ${validation.virusTotal.malicious || 0}/${validation.virusTotal.total || 0} engines flagged as malicious\n`;
  }
  
  if (validation.urlhaus && !validation.urlhaus.error) {
    result += `• URLhaus: ${validation.urlhaus.isPhish ? 'Confirmed malicious site' : 'Not in database'}\n`;
    if (validation.urlhaus.threat) {
      result += `  Threat type: ${validation.urlhaus.threat}\n`;
    }
    if (validation.urlhaus.tags && validation.urlhaus.tags.length > 0) {
      result += `  Tags: ${validation.urlhaus.tags.join(', ')}\n`;
    }
  }
  
  return result;
}

function generateEmailHTML(report, reason) {
  return `
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #d32f2f;">🚨 AUTOMATED PHISHING REPORT</h2>
      
      <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <strong>Malicious URL:</strong> <code>${report.url}</code><br>
        <strong>Risk Score:</strong> <span style="color: #d32f2f; font-weight: bold;">${report.riskScore}/100</span><br>
        <strong>Risk Level:</strong> ${report.riskLevel}<br>
        <strong>Detection Date:</strong> ${new Date(report.createdAt).toLocaleString()}<br>
        <strong>Status:</strong> ${report.status.replace('_', ' ').toUpperCase()}
      </div>

      <h3>Risk Analysis Details:</h3>
      <div style="background-color: #fff3cd; padding: 10px; border-left: 4px solid #ffc107;">
        ${formatRiskChecks(report.riskChecks).replace(/\n/g, '<br>').replace(/•/g, '&#8226;')}
      </div>

      ${report.validationResults ? `
      <h3>Third-party Validation:</h3>
      <div style="background-color: #d1ecf1; padding: 10px; border-left: 4px solid #bee5eb;">
        ${formatValidationResults(report.validationResults).replace(/\n/g, '<br>').replace(/•/g, '&#8226;')}
      </div>
      ` : ''}

      <p style="margin-top: 30px;">
        This automated report is generated by our phishing detection system. 
        Please investigate and take appropriate action to protect users from this potential threat.
      </p>

      <hr style="margin: 30px 0;">
      <p style="color: #6c757d; font-size: 12px;">
        This is an automated message from our security monitoring system.<br>
        For questions or additional information, please contact our security team.
      </p>
    </body>
    </html>
  `;
}